server:
  port: 9999 #端口
  servlet:
    context-path: /ems-thymeleaf #项目名


spring:

  thymeleaf:
    cache: false # 关闭缓存
    prefix: classpath:/templates/ #指定模板位置
    suffix: .html #指定后缀

  #整合mybatis
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ems-thymeleaf?characterEncoding=UTF-8
    username: root
    password: password

  web:
    resources:
      static-locations: classpath:/static/,file:${photo.file.dir} #暴露哪些资源可以通过项目名访问

#mybatis
mybatis:
  mapper-locations: classpath:com/hxh/emsthymeleaf/mapper/*.xml #mapper文件位置
  type-aliases-package: com.hxh.emsthymeleaf.entity #实体类的包名

#IDEA右上角：Edit Configurations，点击，找到VM options，填入-Dspring.output.ansi.enabled=ALWAYS。重新启动应用，就会发现控制台日志变成彩色了
#配置日志
logging:
  level:
    root: info #调整全局日志展示，默认为：info,一般不要改
    com.hxh.emsthymeleaf: debug #输出指定包的日志级别
  file:
    name: run.log #指定生成日志文件名称
    path: ./ #将日志文件生成到当前目录

#指定文件上传位置
photo:
  file:
    dir: C:\Users\hxsz\IdeaProjects\ems-thymeleaf\photos